### PR TITLE
Feature email ignore list

### PR DESCRIPTION
**Pull request by svrhovac**
The request is to extend configuration with ignore list option.
Post login action and just before sending an email to a user, an ignore list is consulted.
If user profile email is listed, the email would not be sent.

### CODE REVIEW

**Comment by wax100** [comment]
@svrhovac can U delete **info@info.com** from default config?

**Comment by svrhovac** [comment]
> @svrhovac can U delete **[info@info.com](mailto:info@info.com)** from default config?

Done.

**Comment by wax100** [comment]
@svrhovac 
can U also change version file and generate new package please?

**Comment by wax100** [comment]
@svrhovac
Any changes?

**Comment by svrhovac** [comment]
Hi @wax100 ,
Configuration updated with new version.
A new package generated.

**Comment by wax100** [comment]
@svrhovac merged! thank you 
can U add this extra to Repo?

**Pull request merged**
